//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualBazaar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertiserRegisteration
    {
        public int AdvertiserID { get; set; }
        public string OrganisationName { get; set; }
        public int Category { get; set; }
        public string Street { get; set; }
        public int LocalityID { get; set; }
        public string Landmark { get; set; }
        public int CityID { get; set; }
        public int StateID { get; set; }
        public string Country { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobileNum { get; set; }
        public string CustomerEmailID { get; set; }
        public string Image { get; set; }
        public string Scheme { get; set; }
        public int ViewsAllowed { get; set; }
        public string Keyword { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<int> MobileStatus { get; set; }
    }
}
