//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualBazaar
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvertiserVideo
    {
        public int VideoID { get; set; }
        public int AdvertiserID { get; set; }
        public string Title { get; set; }
        public string Extension { get; set; }
        public string ContentType { get; set; }
        public System.TimeSpan Duration { get; set; }
        public int ApprovalStatus { get; set; }
        public int ActiveStatus { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Video { get; set; }
    }
}
