//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualBazaar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class BazaarModelContainer : DbContext
    {
        public BazaarModelContainer()
            : base("name=BazaarModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserInfo> UserInfoes { get; set; }
        public DbSet<AdvertiserVideo> AdvertiserVideos { get; set; }
        public DbSet<AdvertiserRegisteration> AdvertiserRegisterations { get; set; }
        public DbSet<AdvertiserCategory> AdvertiserCategories { get; set; }
        public DbSet<Locality> Localities { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<VideoVisitor> VideoVisitors { get; set; }
        public DbSet<VideoComment> VideoComments { get; set; }
        public DbSet<VideoRating> VideoRatings { get; set; }
        public DbSet<VideosApproval> VideosApprovals { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<Menupermission> Menupermissions { get; set; }
        public DbSet<Coupon> Coupons { get; set; }
    
        public virtual ObjectResult<Nullable<decimal>> GetIdentity(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("TableName", tableName) :
                new ObjectParameter("TableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("GetIdentity", tableNameParameter);
        }
    }
}
