//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualBazaar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menupermission
    {
        public int MenuID { get; set; }
        public int User_Recno { get; set; }
        public int EditviewRight { get; set; }
        public int MenuId { get; set; }
    }
}
