//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualBazaar
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoRating
    {
        public int RatingID { get; set; }
        public int VideoID { get; set; }
        public int Rating { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
    }
}
